### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by dellagustin** [podStation/podStation#47]
Automated tests are running consistently on the travis build, but they work fine locally

https://travis-ci.org/podStation/podStation/builds/641679707

![image](https://user-images.githubusercontent.com/260113/73120198-7aa67000-3f6b-11ea-947a-d9263af45919.png)

**Comment by dellagustin** [comment]
The errors seem to be all related to `jsmediatags`:

```
HeadlessChrome 0.0.0 (Linux 0.0.0) audioPlayerService play should persist playback rate and use it on next play FAILED
	ReferenceError: jsmediatags is not defined
	    at <Jasmine>
	    at getAudioTags (extension/background/entities/audioPlayer.js:170:4)
	    at play (extension/background/entities/audioPlayer.js:303:5)
	    at extension/background/entities/audioPlayer.js:461:4
	    at extension/reuse/messageServiceDefinition.js:42:19
	    at <Jasmine>
	    at dispatchToListeners (extension/reuse/messageServiceDefinition.js:41:33)
	    at MessageRelayer.sendMessage (extension/reuse/messageServiceDefinition.js:72:6)
	    at UserContext.<anonymous> (spec/background/audioPlayerService.spec.js:163:38)
	    at <Jasmine>
```

**Comment by dellagustin** [comment]
I cloned a clean repo and run the installation steps, got the following error:
```
 ./copy_dependencies.sh
cp: cannot stat 'bower_components/jsmediatags/dist/jsmediatags.js': No such file or directory
```
here is the culprit...

**Comment by dellagustin** [comment]
I found what caused the issue: https://github.com/aadsm/jsmediatags/commit/aab8bb0951f3b7c95aeb4a8e37b3f7e59b2c6653#diff-0a08a7565aba4405282251491979bb6b

A change in the bower config file with respect to distribution (curiously, it retroactively affected my dependency version).

I created a issue in the jsmediatags project just to inform them: https://github.com/aadsm/jsmediatags/issues/125
